- invoice_number : 'KA-B1-77166244'
  month : 'Jul'
  year : '2022'
  invoice_date : '01/07/2022'
  due_date : '15/07/2022'
  end_date : '31/07/2022'
  number_of_days : '31'

- invoice_number : 'KA-B1-78772304'
  month : 'Aug'
  year : '2022'
  invoice_date : '01/08/2022'
  due_date : '15/08/2022'
  end_date : '31/08/2022'
  number_of_days : '31'

- invoice_number : 'KA-B1-81178651'
  month : 'Sep'
  year : '2022'
  invoice_date : '01/09/2022'
  due_date : '15/09/2022'
  end_date : '30/09/2022'
  number_of_days : '30'

- invoice_number : 'KA-B1-83397597'
  month : 'Oct'
  year : '2022'
  invoice_date : '01/10/2022'
  due_date : '15/10/2022'
  end_date : '31/10/2022'
  number_of_days : '31'

- invoice_number : 'KA-B1-85310676'
  month : 'Nov'
  year : '2022'
  invoice_date : '01/11/2022'
  due_date : '15/11/2022'
  end_date : '30/11/2022'
  number_of_days : '30'

- invoice_number : 'KA-B1-98930054'
  month : 'Dec'
  year : '2022'
  invoice_date : '01/12/2022'
  due_date : '15/12/2022'
  end_date : '31/12/2022'
  number_of_days : '31'

- invoice_number : 'KA-B1-99934829'
  month : 'Jan'
  year : '2023'
  invoice_date : '01/01/2023'
  due_date : '15/01/2023'
  end_date : '31/01/2023'
  number_of_days : '31'

- invoice_number : 'KA-B1-99993940'
  month : 'Feb'
  year : '2023'
  invoice_date : '01/02/2023'
  due_date : '15/02/2023'
  end_date : '28/02/2023'
  number_of_days : '28'

- invoice_number : 'KA-B1-99974829'
  month : 'Mar'
  year : '2023'
  invoice_date : '01/03/2023'
  due_date : '15/03/2023'
  end_date : '31/03/2023'
  number_of_days : '31'

- invoice_number : 'KA-B1-99984854'
  month : 'April'
  year : '2023'
  invoice_date : '01/04/2023'
  due_date : '15/04/2023'
  end_date : '30/04/2023'
  number_of_days : '30'

- invoice_number : 'KA-B1-99984849'
  month : 'May'
  year : '2023'
  invoice_date : '01/05/2023'
  due_date : '15/05/2023'
  end_date : '31/05/2023'
  number_of_days : '31'

- invoice_number : 'KA-B1-99998798'
  month : 'June'
  year : '2023'
  invoice_date : '01/06/2023'
  due_date : '15/06/2023'
  end_date : '30/06/2023'
  number_of_days : '30'

- invoice_number : 'KA-B1-99998902'
  month : 'Jul'
  year : '2023'
  invoice_date : '01/07/2023'
  due_date : '15/07/2023'
  end_date : '31/07/2023'
  number_of_days : '31'

- invoice_number : 'KA-B1-99999002'
  month : 'Aug'
  year : '2023'
  invoice_date : '01/08/2023'
  due_date : '15/08/2023'
  end_date : '31/08/2023'
  number_of_days : '31'

- invoice_number : 'KA-B1-99999110'
  month : 'Sep'
  year : '2023'
  invoice_date : '01/09/2023'
  due_date : '15/09/2023'
  end_date : '30/09/2023'
  number_of_days : '30'

- invoice_number : 'KA-B1-99999112'
  month : 'Oct'
  year : '2023'
  invoice_date : '01/10/2023'
  due_date : '15/10/2023'
  end_date : '31/10/2023'
  number_of_days : '31'
